apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-environment
  namespace: default
data:
  QUARKUS_PROFILE: local
---
apiVersion: v1
kind: Secret
metadata:
  name: shared-environment
type: Opaque