---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: card
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card
  template:
    metadata:
      labels:
        app: card
    spec:
      containers:
        - name: card
          image: olaaref/card
          imagePullPolicy: Never
          resources:
            requests:
              memory: 500Mi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: 1
          envFrom:
            - configMapRef:
                name: shared-environment
            - secretRef:
                name: shared-environment

          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: card
  labels:
    name: card
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: card
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: card
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /api/v1/card/$1
    nginx.ingress.kubernetes.io/cors-allow-origin: https://localhost:4200
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
    - http:
        paths:
          - path: /api/v1/card/(.*)
            pathType: Prefix
            backend:
              service:
                name: card
                port:
                  number: 80